const PHRASES = {
    errorSelectCustomerAndProject: 'Please select customer and project',
    errorSelectCustomer: 'please select at least customer, or customer and project',
    errorCustomerAvailable: 'Open up your eyes dear, this customer is already available!',
    errorProjectAvailable: 'Check it babe, this project is already available!',
    confirmDeleteCustomer: 'Do you know what you are doing dear? Delete customer ${customer} and all depending projects and times?',
    confirmDeleteProject: 'Oh-oh, sure you want to delete project ${project} with all it\'s times?',
    confirmDeleteTime: 'Here we go, delete time record ${time} for ever?',
    errorEntryCustomer: 'Please add customer!',
    errorEntryProject: 'Please add project!',
    addCustomer: 'Add customer',
    addProject: 'Add project',
    headerCustomer: 'Please select a customer',
    headerProject: 'Please select a project',
    placeholderCustomer: 'Customer',
    placeholderProject: 'Project',
    customer: 'Customer',
    project: 'Project',
    startDate: 'Startdate',
    endDate: 'Enddate',
    startTime: 'Starttime',
    endTime: 'Endtime',
    duration: 'Duration',
    allYears: 'All years',
    allMonth: 'All months',
    filterTimes: 'Filter time records',
    errorFilter: 'No time records available for this period',
    export: 'Export time records as csv file',
    selectLanguage: 'Select language',
    selectedFormat: 'Select date format',
    dateFormat: 'Dateformat',
    timeFormat24Hours: 'Timeformat 24 hrs: hh:mm',
    timeFormat12Hours: 'Timeformat 12 hrs: hh:mm AM/PM',
}

export default PHRASES;
