const PHRASES = {
    errorSelectCustomerAndProject: 'Please select customer and project',
    errorSelectCustomer: 'please select at least customer, or customer and project',
    errorCustomerAvailable: 'Ja schau halt hin, den Kunden gibt es doch schon!',
    errorProjectAvailable: 'Dieses Projekt gibt es schon!',
    confirmDeleteCustomer: 'Echt jetzt, Kunde ${customer} mit allen Projekten und Zeiten löschen?',
    confirmDeleteProject: 'OK, das möchte ich jetzt lieber schriftlich... Projekt ${project} mit allen Zeiten komplett löschen?',
    confirmDeleteTime: 'Was denn, die Zeiterfassung vom ${time} echt löschen?',
    errorEntryCustomer: 'Bitte Kunden eintragen!',
    errorEntryProject: 'Bitte Projekt eintragen!',
    addCustomer: 'Kunde anlegen',
    addProject: 'Projekt anlegen',
    headerCustomer: 'Bitte Kunden wählen',
    headerProject: 'Bitte Projekt wählen',
    placeholderCustomer: 'Kunde',
    placeholderProject: 'Projekt',
    customer: 'Kunde',
    project: 'Projekt',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    startTime: 'Startzeit',
    endTime: 'Endzeit',
    duration: 'Dauer',
    allYears: 'Alle Jahre',
    allMonth: 'Alle Monate',
    filterTimes: 'Zeiten filtern',
    errorFilter: 'Für diesem Zeitraum sind keine Zeiten verfügbar',
    export: 'Zeiten als csv Datei exportieren',
    selectLanguage: 'Sprache wählen',
    selectedFormat: 'Datumsformat wählen',
    dateFormat: 'Datumsformat',
    timeFormat24Hours: 'Zeitformat 24 h, hh:mm',
    timeFormat12Hours: 'Zeitformat 12 h, hh:mm AM/PM',
}

export default PHRASES;
